/**
 * Feeder congestion recommendations for the utility dashboard. Given a snapshot
 * of feeders (code, congestion level, utilisation), it returns the THREE
 * highest-priority grid actions — generated by Google AI Studio (Gemini) when a
 * key is configured, and by a deterministic severity ranking otherwise, so the
 * panel always renders something useful even offline / rate-limited.
 */
import { env } from "@/lib/env";

export type FeederSnapshot = {
  code: string;
  name: string;
  congestionLevel: "low" | "risky" | "high" | "critical";
  loadPct: number;
  availableSurplusKwh: number;
  capacityKw: number;
  meterCount: number;
};

export type Recommendation = {
  feederCode: string;
  priority: "critical" | "high" | "risky" | "low";
  action: string; // one concrete grid action
  rationale: string; // one short sentence
};

export type RecommendationResult = {
  source: "ai" | "rules";
  model?: string;
  reason?: string; // why we fell back to rules, when applicable
  recommendations: Recommendation[];
};

const GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models";
const SEVERITY_RANK: Record<FeederSnapshot["congestionLevel"], number> = {
  critical: 3, high: 2, risky: 1, low: 0,
};

export function isGeminiConfigured(): boolean {
  return env.geminiApiKeys().length > 0;
}

/** Feeders ranked most-congested first — the shared basis for AI and fallback. */
function rankBySeverity(feeders: FeederSnapshot[]): FeederSnapshot[] {
  return [...feeders].sort(
    (a, b) =>
      SEVERITY_RANK[b.congestionLevel] - SEVERITY_RANK[a.congestionLevel] ||
      b.loadPct - a.loadPct,
  );
}

// Templated action per congestion band, used when Gemini is unavailable.
function fallbackAction(f: FeederSnapshot): { action: string; rationale: string } {
  const pct = `${f.loadPct.toFixed(0)}%`;
  switch (f.congestionLevel) {
    case "critical":
      return { action: "Curtail export, dispatch storage", rationale: `${pct} — over capacity` };
    case "high":
      return { action: "Pre-stage storage / DR", rationale: `${pct} — near overload` };
    case "risky":
      return { action: "Shift flexible load here", rationale: `${pct} — headroom tightening` };
    default:
      return { action: "Route new demand here", rationale: `${pct} — spare capacity` };
  }
}

function fallbackRecommendations(feeders: FeederSnapshot[], reason?: string): RecommendationResult {
  const top = rankBySeverity(feeders).slice(0, 3);
  return {
    source: "rules",
    reason,
    recommendations: top.map((f) => ({
      feederCode: f.code,
      priority: f.congestionLevel,
      ...fallbackAction(f),
    })),
  };
}

const SYSTEM_PROMPT = `You are a grid operations advisor for Shakti, a rooftop-solar feeder network in Gandhinagar, India. You are given feeders with their congestion level and utilisation (available surplus as a percentage of capacity: <70% low, 70-90% risky, 90-100% high, >100% critical — a high figure means too much unabsorbed solar surplus / reverse-flow risk).

Return EXACTLY 3 recommendations, the highest-priority grid actions right now, most urgent first. Prioritise critical then high then risky feeders; use a low feeder only if it has spare capacity to relieve a congested one. Actions must be concrete grid moves (curtail export, dispatch/charge storage, shift or route flexible load, transfer load). BE TERSE: action at most 6 words, rationale at most 6 words.

Return ONLY a JSON object of this exact shape:
{"recommendations":[{"feederCode": a code copied EXACTLY from the input,"priority": one of ["critical","high","risky","low"],"action": imperative phrase, ≤6 words,"rationale": ≤6 words citing the number}]}
Never invent a feeder code. Exactly 3 items.`;

type RawRec = { feederCode?: string; priority?: string; action?: string; rationale?: string };
const PRIORITIES = ["critical", "high", "risky", "low"] as const;

/** Coerce Gemini's JSON into valid recommendations; drop unknown feeder codes. */
function sanitize(raw: RawRec[], known: Map<string, FeederSnapshot>): Recommendation[] {
  const out: Recommendation[] = [];
  for (const r of raw) {
    const code = String(r.feederCode ?? "");
    const feeder = known.get(code);
    if (!feeder) continue; // anti-hallucination: must be a real feeder
    const priority = (PRIORITIES as readonly string[]).includes(r.priority ?? "")
      ? (r.priority as Recommendation["priority"])
      : feeder.congestionLevel;
    out.push({
      feederCode: code,
      priority,
      action: String(r.action ?? "").slice(0, 160),
      rationale: String(r.rationale ?? "").slice(0, 200),
    });
  }
  return out.slice(0, 3);
}

/** Call Gemini generateContent, rotating keys on rate-limit/auth failures. */
async function callGemini(payload: string): Promise<string> {
  const keys = env.geminiApiKeys();
  const model = env.geminiModel();
  let lastErr: unknown;

  for (const key of keys) {
    try {
      const res = await fetch(`${GEMINI_URL}/${model}:generateContent`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-goog-api-key": key },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] },
          contents: [{ parts: [{ text: `Feeders:\n${payload}` }] }],
          generationConfig: { temperature: 0, responseMimeType: "application/json", maxOutputTokens: 8192 },
        }),
      });
      if (res.status === 429 || res.status === 401 || res.status === 403) {
        lastErr = new Error(`Gemini key rejected (${res.status})`);
        continue; // try the next key in the pool
      }
      if (!res.ok) throw new Error(`Gemini error ${res.status}: ${(await res.text()).slice(0, 200)}`);
      const data = (await res.json()) as {
        candidates?: { content?: { parts?: { text?: string }[] } }[];
      };
      const text = data.candidates?.[0]?.content?.parts?.map((p) => p.text ?? "").join("") ?? "";
      if (!text) throw new Error("Gemini returned no text");
      return text;
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error("All Gemini keys failed");
}

/** Top-3 priority feeder actions — Gemini when configured, rules otherwise. */
export async function recommendFeederActions(feeders: FeederSnapshot[]): Promise<RecommendationResult> {
  if (feeders.length === 0) return { source: "rules", recommendations: [] };
  if (!isGeminiConfigured()) return fallbackRecommendations(feeders, "Gemini not configured");

  // Send only the congested-first feeders to keep the prompt small (TPM-friendly).
  const ranked = rankBySeverity(feeders);
  const known = new Map(feeders.map((f) => [f.code, f]));
  const payload = JSON.stringify(
    ranked.slice(0, 12).map((f) => ({
      code: f.code,
      name: f.name,
      congestion: f.congestionLevel,
      utilisationPct: Number(f.loadPct.toFixed(1)),
      availableSurplusKwh: Number(f.availableSurplusKwh.toFixed(1)),
      capacityKw: f.capacityKw,
      meters: f.meterCount,
    })),
  );

  let text: string;
  try {
    text = await callGemini(payload);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Gemini unavailable";
    return fallbackRecommendations(feeders, /429/.test(msg) ? "Gemini rate-limited" : msg);
  }

  let parsed: { recommendations?: RawRec[] };
  try {
    parsed = JSON.parse(text);
  } catch {
    return fallbackRecommendations(feeders, "Gemini returned invalid JSON");
  }
  const recs = sanitize(Array.isArray(parsed.recommendations) ? parsed.recommendations : [], known);
  if (recs.length === 0) return fallbackRecommendations(feeders, "Gemini returned no usable actions");

  return { source: "ai", model: env.geminiModel(), recommendations: recs };
}
